cloud_id                 = "b1grlpn15e2p3lga3oig"
folder_id                = "b1gabf9ceva9db98unsh"
zone                     = "ru-central1-a"
image_id                 = "fd8b5dv5717qede4og1q"
public_key_path          = "~/.ssh/appuser.pub"
subnet_id                = "e9bloi131i8uqopjcnkr"
service_account_key_file = "key.json"
private_key              = "~/.ssh/appuser"
